services:
  postgres:
    image: ankane/pgvector:latest # Changed to pgvector-enabled PostgreSQL
    container_name: pg-newsinsight
    env_file:
      - ./.env
    ports:
      - "5432:5432" # change left side if 5432 is busy, e.g. "55432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - newsinsight-net

  pgadmin:
    image: dpage/pgadmin4:8.11
    container_name: pgadmin-newsinsight
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newsinsight.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - newsinsight-net

volumes:
  pg_data:

networks:
  newsinsight-net:
    external: true
